# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/igm-analysis
  docker:
    - image: circleci/node:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: 
          command: |
            npm i tap-xunit
            mkdir -p ~/reports/riteway
            node -r @babel/register -r regenerator-runtime/runtime index.test.js | npx tap-xunit > ~/reports/riteway/test-results.xml 
          when: always

      - store_test_results:
          path: ~/reports

      - store_artifacts:
          path: ~/reports 

      - persist_to_workspace:
          root: ~/igm-analysis
          paths: .
